name: Daily Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche UTC
    
jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: zip -r backup_$(date +'%Y-%m-%d').zip .

      - name: Upload Backup
        uses: actions/upload-artifact@v2
        with:
          name: backup-$(date +'%Y-%m-%d').zip
          path: backup_$(date +'%Y-%m-%d').zip
